export { createExtensia } from "./public/extensia.js";
export { defineFullResourceDriver } from "./public/full-resource-driver.js";
export type {
  FullResourceDriver,
  FullResourceDriverDefinition,
} from "./public/full-resource-driver.js";
export type {
  AssetSnapshot,
  ExtensiaConfig,
  ExtensiaError,
  ExtensiaErrorCode,
  ExtensiaInspection,
  ExtensiaModule,
  ExtensiaModuleState,
  ExtensiaResult,
  CreateResourceInput,
  UpdateResourceInput,
  IDString,
  JSONArray,
  JSONObject,
  JSONPrimitive,
  JSONValue,
  MarkSnapshot,
  MoveResourceInput,
  QueryFacade,
  ReadonlyResourceDriver,
  ResourceChildRefSnapshot,
  ResourceDataSnapshot,
  ResourceKVSnapshot,
  ResourceMoveError,
  ResourceMoveResult,
  ResourceDeleteError,
  ResourceDeleteResult,
  ResourceSnapshot,
  ResourceTreeViewSnapshot,
  ResourceWriteError,
  ResourceWriteSuccess,
  ResourceWriteWarning,
  ResourceWriteWarningCode,
  SafeDiagnostic,
  SetMarkInput,
  ResourceMarksError,
  ResourceMarksResult,
  ResourceKVError,
  ResourceKVResult,
  StorageFacade,
  Timestamp,
} from "./public/contracts.js";
